In [1]:
import numpy as np

In [2]:
a = np.array([1, 2])

In [3]:
a

array([1, 2])

In [4]:
a.fill(0)

In [5]:
a

array([0, 0])

In [6]:
a = np.empty(2)

In [7]:
a

array([ 1.74081286e+62, -6.04773467e-25])

In [8]:
a.fill(1)

In [9]:
a

array([1., 1.])